import * as NodeServices from "@effect/platform-node/NodeServices";
import { describe, expect, it } from "@effect/vitest";
import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";

import { hasLiveMidwaySession, parseNetscapeCookies, readMidwayCookies } from "./MidwayCookies.ts";

const NOW = 1_800_000_000;

const jar = [
  "# Netscape HTTP Cookie File",
  "# https://curl.se/docs/http-cookies.html",
  "# This file was generated by libcurl! Edit at your own risk.",
  "",
  `#HttpOnly_prod.example.aws.dev\tFALSE\t/\tTRUE\t${NOW + 600}\tamzn_sso_token\ttok.en`,
  `.midway-auth.amazon.com\tTRUE\t/\tTRUE\t${NOW + 3600}\tamazon_enterprise_access\tyes`,
  `midway-auth.amazon.com\tFALSE\t/\tTRUE\t${NOW + 86_400}\tuser_name\talice`,
  `#HttpOnly_midway-auth.amazon.com\tFALSE\t/\tTRUE\t${NOW + 72_000}\tsession\tabc\tdef`,
  `#HttpOnly_midway-auth.amazon.com\tFALSE\t/\tTRUE\t${NOW + 72_000}\t__Host-session\txyz`,
  `stale.example.com\tFALSE\t/\tFALSE\t${NOW - 1}\told\tgone`,
  `session.example.com\tFALSE\t/app\tFALSE\t0\tsid\tkeep`,
  "not-enough\tcolumns",
].join("\n");

describe("parseNetscapeCookies", () => {
  it("maps rows to Electron cookies and drops comments, short rows and expired cookies", () => {
    const parsed = parseNetscapeCookies(jar, NOW);
    expect(parsed.expired).toBe(1);
    expect(parsed.cookies.map((cookie) => cookie.name)).toEqual([
      "amzn_sso_token",
      "amazon_enterprise_access",
      "user_name",
      "session",
      "__Host-session",
      "sid",
    ]);
  });

  it("honours the HttpOnly marker and the secure flag", () => {
    const parsed = parseNetscapeCookies(jar, NOW);
    const token = parsed.cookies.find((cookie) => cookie.name === "amzn_sso_token")!;
    expect(token.httpOnly).toBe(true);
    expect(token.secure).toBe(true);
    expect(token.url).toBe("https://prod.example.aws.dev/");
    const userName = parsed.cookies.find((cookie) => cookie.name === "user_name")!;
    expect(userName.httpOnly).toBe(false);
  });

  it("keeps a host-only cookie host-only and a dotted host as a domain cookie", () => {
    const parsed = parseNetscapeCookies(jar, NOW);
    const session = parsed.cookies.find((cookie) => cookie.name === "session")!;
    expect(session.domain).toBeUndefined();
    expect(session.url).toBe("https://midway-auth.amazon.com/");
    const access = parsed.cookies.find((cookie) => cookie.name === "amazon_enterprise_access")!;
    expect(access.domain).toBe(".midway-auth.amazon.com");
  });

  it("rejoins values that contain tabs and treats expiry 0 as a session cookie", () => {
    const parsed = parseNetscapeCookies(jar, NOW);
    expect(parsed.cookies.find((cookie) => cookie.name === "session")!.value).toBe("abc\tdef");
    const sid = parsed.cookies.find((cookie) => cookie.name === "sid")!;
    expect(sid.expirationDate).toBeUndefined();
    expect(sid.path).toBe("/app");
    expect(sid.url).toBe("http://session.example.com/app");
  });

  it("uses an unspecified SameSite since the format carries none", () => {
    const parsed = parseNetscapeCookies(jar, NOW);
    expect(new Set(parsed.cookies.map((cookie) => cookie.sameSite))).toEqual(
      new Set(["unspecified"]),
    );
  });
});

describe("hasLiveMidwaySession", () => {
  it("is true when the midway-auth session cookie is present and unexpired", () => {
    expect(hasLiveMidwaySession(parseNetscapeCookies(jar, NOW))).toBe(true);
  });

  it("is false once the session cookie has lapsed", () => {
    expect(hasLiveMidwaySession(parseNetscapeCookies(jar, NOW + 72_001))).toBe(false);
  });

  it("is false for a jar with no midway-auth cookies", () => {
    const other = `example.com\tFALSE\t/\tTRUE\t${NOW + 10}\tsession\tx`;
    expect(hasLiveMidwaySession(parseNetscapeCookies(other, NOW))).toBe(false);
  });
});

describe("readMidwayCookies", () => {
  it.effect("reads and parses a jar from disk", () =>
    Effect.gen(function* () {
      const fileSystem = yield* FileSystem.FileSystem;
      const directory = yield* fileSystem.makeTempDirectoryScoped({ prefix: "t3code-midway-" });
      const file = `${directory}/cookie`;
      yield* fileSystem.writeFileString(file, jar);
      const parsed = yield* readMidwayCookies(file, NOW);
      expect(parsed.cookies).toHaveLength(6);
      expect(parsed.expired).toBe(1);
    }).pipe(Effect.scoped, Effect.provide(NodeServices.layer)),
  );

  it.effect("fails with a tagged error when the jar is missing", () =>
    Effect.gen(function* () {
      const result = yield* readMidwayCookies("/nonexistent/midway/cookie", NOW).pipe(Effect.flip);
      expect(result._tag).toBe("MidwayCookieReadError");
    }).pipe(Effect.provide(NodeServices.layer)),
  );
});
